FROM restic/restic:0.17.3@sha256:56a38e9a95f8b55e7799ba262c6015d0c00f09316e4d1e8c256ab4b1959fb0a3 AS restic
FROM python:3.12.10-slim@sha256:4c2cf9917bd1cbacc5e9b07320025bdb7cdf2df7b0ceaccb55e9dd7e30987419
COPY --from=restic /usr/bin/restic /usr/local/bin/restic
RUN groupadd --system --gid 10001 backup && useradd --system --uid 10001 --gid backup --home /staging backup && mkdir -p /staging && chown backup:backup /staging
USER 10001:10001
ENTRYPOINT ["/bin/sh","/scripts/backup-loop.sh"]
